"""
Parses cleaned_subjects_raw.xlsx and generates a SQL seed script.

Excel structure (Sheet1):
  Row 0: Title row
  Row 1: Max marks: col4=50, col5=50, col6=100, col7=100
  Row 2: Pass marks: col4=25, col5=25, col6=50, col7=50
  Row 3: Column headers
  Row 4: Subject ordinals (1,2,3,4)
  Row 5: Empty
  Row 6+: Data rows:
    col[0] = م (serial)
    col[1] = المهنة
    col[2] = النظام (exam system)
    col[3] = المجموعة المهنية
    col[4] = Subject 1 name (max=50, pass=25)
    col[5] = Subject 2 name (max=50, pass=25)
    col[6] = Subject 3 name (max=100, pass=50)
    col[7] = Subject 4 name (max=100, pass=50)
"""

import openpyxl

EXCEL_PATH = r"cleaned_subjects_raw.xlsx"
OUTPUT_SQL = r"seed_subjects_from_excel.sql"

# Max/pass marks per subject slot (from rows 1 & 2)
SUBJECT_SLOTS = [
    {"max": 50,  "pass": 25},
    {"max": 50,  "pass": 25},
    {"max": 100, "pass": 50},
    {"max": 100, "pass": 50},
]

def esc(s):
    """Escape single quotes for Oracle SQL."""
    if s is None:
        return None
    return str(s).strip().replace("'", "''")

wb = openpyxl.load_workbook(EXCEL_PATH)
ws = wb.active

rows = list(ws.iter_rows(values_only=True))

# Collect parsed data starting from row index 6
parsed = []
for row in rows[6:]:
    # Skip empty rows
    if row[1] is None:
        continue
    serial       = row[0]
    profession   = str(row[1]).strip() if row[1] else None
    exam_system  = str(row[2]).strip() if row[2] else None
    prof_group   = str(row[3]).strip() if row[3] else None
    subjects_raw = [row[4], row[5], row[6], row[7]]
    
    if not profession:
        continue

    parsed.append({
        "profession":  profession,
        "exam_system": exam_system,
        "prof_group":  prof_group,
        "subjects":    subjects_raw,
    })

# Unique professional groups + professions
prof_groups = list({r["prof_group"] for r in parsed if r["prof_group"]})
professions = {r["profession"]: r for r in parsed}  # name -> row

print(f"Found {len(prof_groups)} professional groups")
print(f"Found {len(professions)} unique professions")
total_subj = sum(1 for r in parsed for s in r["subjects"] if s)
print(f"Found {total_subj} total subjects")

lines = []
lines.append("-- ============================================================")
lines.append("-- AUTO-GENERATED SQL from cleaned_subjects_raw.xlsx")
lines.append("-- Generated by generate_subjects_sql.py")
lines.append("-- Uses MERGE to avoid duplicates")
lines.append("-- ============================================================")
lines.append("")

# 1. Professional Groups
lines.append("-- 1. Professional Groups")
for pg in sorted(prof_groups):
    safe_pg = esc(pg)
    lines.append(
        f"MERGE INTO professional_groups pg USING (SELECT '{safe_pg}' AS n FROM DUAL) src\n"
        f"  ON (TRIM(pg.name) = TRIM(src.n))\n"
        f"  WHEN NOT MATCHED THEN INSERT (name) VALUES (src.n);"
    )

lines.append("")
lines.append("-- 2. Professions (linked to their Professional Group)")
for profession, row in sorted(professions.items()):
    safe_prof  = esc(profession)
    safe_pg    = esc(row["prof_group"])
    safe_sys   = esc(row["exam_system"])
    
    if safe_pg:
        lines.append(
            f"MERGE INTO professions p USING (\n"
            f"  SELECT '{safe_prof}' AS n, '{safe_sys}' AS sys,\n"
            f"         (SELECT id FROM professional_groups WHERE TRIM(name) = TRIM('{safe_pg}')) AS pgid\n"
            f"  FROM DUAL\n"
            f") src ON (TRIM(p.name) = TRIM(src.n))\n"
            f"WHEN NOT MATCHED THEN INSERT (name, professional_group_id, exam_system) VALUES (src.n, src.pgid, src.sys);"
        )
    else:
        lines.append(
            f"MERGE INTO professions p USING (SELECT '{safe_prof}' AS n, '{safe_sys}' AS sys FROM DUAL) src\n"
            f"  ON (TRIM(p.name) = TRIM(src.n))\n"
            f"  WHEN NOT MATCHED THEN INSERT (name, exam_system) VALUES (src.n, src.sys);"
        )

lines.append("")
lines.append("-- 3. Specializations (one per profession, used by subjects FK)")
for profession in sorted(professions.keys()):
    safe_prof = esc(profession)
    lines.append(
        f"MERGE INTO specializations s USING (\n"
        f"  SELECT '{safe_prof}' AS n,\n"
        f"         (SELECT MIN(id) FROM departments) AS did\n"
        f"  FROM DUAL\n"
        f") src ON (TRIM(s.name) = TRIM(src.n))\n"
        f"WHEN NOT MATCHED THEN INSERT (department_id, name, description)\n"
        f"  VALUES (src.did, src.n, 'تم الإنشاء من بيانات المهن');"
    )

lines.append("")
lines.append("-- 4. Subjects (linked to specialization + profession text column)")
for row in parsed:
    profession  = row["profession"]
    safe_prof   = esc(profession)
    for idx, subj_name in enumerate(row["subjects"]):
        if not subj_name:
            continue
        safe_name  = esc(subj_name)
        max_mark   = SUBJECT_SLOTS[idx]["max"]
        pass_mark  = SUBJECT_SLOTS[idx]["pass"]
        disp_order = idx + 1
        lines.append(
            f"MERGE INTO subjects s USING (\n"
            f"  SELECT '{safe_name}' AS n,\n"
            f"         '{safe_prof}' AS prof,\n"
            f"         {max_mark} AS mx,\n"
            f"         {pass_mark} AS pm,\n"
            f"         {disp_order} AS dord,\n"
            f"         (SELECT MIN(id) FROM specializations WHERE TRIM(name) = TRIM('{safe_prof}')) AS specid\n"
            f"  FROM DUAL\n"
            f") src ON (TRIM(s.name) = TRIM(src.n) AND TRIM(s.profession) = TRIM(src.prof))\n"
            f"WHEN NOT MATCHED THEN INSERT\n"
            f"  (specialization_id, profession, name, type, pass_mark, max_mark, display_order)\n"
            f"VALUES (src.specid, src.prof, src.n, 'نظري', src.pm, src.mx, src.dord);"
        )

lines.append("")
lines.append("COMMIT;")
lines.append("")

sql_output = "\n".join(lines)
with open(OUTPUT_SQL, "w", encoding="windows-1256") as f:
    f.write(sql_output)

print(f"\nSQL written to: {OUTPUT_SQL}  [encoding: windows-1256]")
print(f"Total SQL lines: {len(lines)}")
