@echo off
echo Starting Access Image Linker Tool...
echo Please wait while the tool builds and starts...
.\apache-maven-3.9.5\bin\mvn compile exec:java -Dexec.mainClass="com.pvtd.students.tools.AccessImageLinker"
pause
